//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.06 at 12:22:25 PM IST 
//


package io.games.swings.componants;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentToolTip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="componentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentImage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentXPos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentYPos" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentDisabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="componentListeners" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormComponent", propOrder = {
    "componentToolTip"
})
public class FormComponent {

    protected String componentToolTip;
    @XmlAttribute(required = true)
    protected String componentName;
    @XmlAttribute(required = true)
    protected String componentType;
    @XmlAttribute
    protected String componentAction;
    @XmlAttribute
    protected String componentImage;
    @XmlAttribute
    protected String componentXPos;
    @XmlAttribute
    protected String componentYPos;
    @XmlAttribute
    protected String componentDisabled;
    @XmlAttribute
    protected String componentListeners;

    /**
     * Gets the value of the componentToolTip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentToolTip() {
        return componentToolTip;
    }

    /**
     * Sets the value of the componentToolTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentToolTip(String value) {
        this.componentToolTip = value;
    }

    /**
     * Gets the value of the componentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * Sets the value of the componentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentName(String value) {
        this.componentName = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentType(String value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the componentAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentAction() {
        return componentAction;
    }

    /**
     * Sets the value of the componentAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentAction(String value) {
        this.componentAction = value;
    }

    /**
     * Gets the value of the componentImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentImage() {
        return componentImage;
    }

    /**
     * Sets the value of the componentImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentImage(String value) {
        this.componentImage = value;
    }

    /**
     * Gets the value of the componentXPos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentXPos() {
        return componentXPos;
    }

    /**
     * Sets the value of the componentXPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentXPos(String value) {
        this.componentXPos = value;
    }

    /**
     * Gets the value of the componentYPos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentYPos() {
        return componentYPos;
    }

    /**
     * Sets the value of the componentYPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentYPos(String value) {
        this.componentYPos = value;
    }

    /**
     * Gets the value of the componentDisabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentDisabled() {
        return componentDisabled;
    }

    /**
     * Sets the value of the componentDisabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentDisabled(String value) {
        this.componentDisabled = value;
    }

    /**
     * Gets the value of the componentListeners property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentListeners() {
        return componentListeners;
    }

    /**
     * Sets the value of the componentListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentListeners(String value) {
        this.componentListeners = value;
    }

}
